// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxgGTyw0kUxVyB-GOQ2KhdE_WHgAkPg3I',
    appId: '1:1015826246021:android:b15cbbad262e5933c23cec',
    messagingSenderId: '1015826246021',
    projectId: 'skytalk-4ec55',
    storageBucket: 'skytalk-4ec55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvYY55h5O_FZUFuwD0ruYX8v5pX-u2Cuc',
    appId: '1:1015826246021:ios:64a3f63a1509981bc23cec',
    messagingSenderId: '1015826246021',
    projectId: 'skytalk-4ec55',
    storageBucket: 'skytalk-4ec55.appspot.com',
    androidClientId: '1015826246021-m8kq0s29nf607bigp9i3sh024og5bfi1.apps.googleusercontent.com',
    iosClientId: '1015826246021-3cprf1r3vindons46u25oa7iad00hbnr.apps.googleusercontent.com',
    iosBundleId: 'frost.portfolio.videoConferenceSkytalk',
  );
}
